.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH HASHDB 1 "MAR 2014" "User Manuals"
.SH NAME
hashdb \- Create and manage block hash databases.
.SH SYNOPSIS
.B hashdb <command>
.SH DESCRIPTION
.B hashdb
provides commands for creating and managing hash databases.
For usage, please type "hashdb -h".
.SH HISTORY
.BR "hashdb" 
was released into the public domain by Bruce Allen in 2013.
.SH AUTHOR
Bruce Allen bdallen nps edu.
.SH REPORTING BUGS
Report bugs to author.
.SH COPYRIGHT
.BR "hashdb" 
code is provided with the following notice:
The software provided here is released by the Naval Postgraduate School,
an agency of the U.S. Department of Navy. The software bears no warranty,
either expressed or implied. NPS does not assume legal liability nor
responsibility for a User's use of the software or the results of such use.

Please note that within the United States, copyright protection,
under Section 105 of the United States Code, Title 17, is not available
for any work of the United States Government and/or for any works
created by United States Government employees. 

.SH SEE ALSO
.BR "hashdb" 
wiki at https://github.com/NPS-DEEP/hashdb/wiki.

