all:
	cd drawings; make
	pdflatex hashdbUsersManual.tex
	pdflatex hashdbUsersManual.tex

clean:
	rm -rf hashdbUsersManual.aux hashdbUsersManual.log hashdbUsersManual.out hashdbUsersManual.pdf hashdbUsersManual.toc

