hashdb_quick_reference.pdf: hashdb_quick_reference.tex hashdb_quick_reference_text.tex
	pdflatex hashdb_quick_reference.tex

clean:
	rm -rf hashdb_quick_reference.aux hashdb_quick_reference.log hashdb_quick_reference.out hashdb_quick_reference.pdf

.PHONY: clean

